#!/bin/bash

while true; do
   echo -e 'BLINK!' | osd_cat -f "-bitstream-*-*-r-*-*-*-1600-*-*-*-*-*-*" \
      --pos=middle --align=CENTER --offset=-400 --delay=1 --color=red --shadow=4
   sleep 300
done &
