#!/usr/bin/env ruby

Signal.trap('INT') {
  exit 0
}

screen_size = `xdpyinfo | grep dimensions | cut -d ' ' -f 7`
screen_x_size,screen_y_size = screen_size.split('x')
screen_x_size = screen_x_size.to_i
screen_y_size = screen_y_size.to_i
y_offset = 100 - screen_y_size

`echo "Process is complete!" |aosd_cat --x-offset=50 --fade-full=1000000 --y-offset=#{y_offset} --font 'Droid Sans 50' --fore-color blue`
