#!/bin/bash
dir=/media/floppy1
for album in $(seq 2 6);do
  echo "### ${dir}/f&j 02-24-07_disc ${album} of 6"
  cd "${dir}/f&j 02-24-07_disc ${album} of 6"
  ufraw-batch --saturation=1.1 --base-curve-file ~/pdoc/wedding/photos/base_curve.curve --out-type=jpeg *
done
