#!/bin/bash
DATE="/bin/date"
HOST=$1
PORT=$2

if [ "$HOST" == "" ]; then
    exit
fi

if [ "$PORT" == "" ]; then
    PORT="443"
fi

CMD=`echo "" | openssl s_client -connect $HOST:$PORT 2>/dev/null | openssl x509 -enddate -noout 2>/dev/null|  sed 's/notAfter\=//'`

if [ "$CMD" != "" ]; then
    EXPIRE_DATE=`$DATE -d "$CMD" +%s`
    TIME=`$DATE +%s`
    EXPIRE_TIME=$(( ($EXPIRE_DATE - $TIME) / 86400))
    echo number of days till expiration: $EXPIRE_TIME
fi
